# Generated by Django 3.2.6 on 2021-08-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created', 'title']},
        ),
    ]
